using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace AmbucareDAL.Repository.DAL.Report
{
    public class R74027DAL : CommonDAL
    {
        public DataTable GetGridAllData(int storeid)
        {
            return Query("SELECT t.ITEM_ID,t.ITEM_NAME,t.UM_NAME,t.STORE_NAME,ROUND(t.UNIT_VALUE,2) UNIT_VALUE,t.ITEM_TYPE,t.RCV_QTY,t.ISSUE_QTY,t.STOCK,t.STOCK * ROUND(t.UNIT_VALUE,2) TVALUE FROM (SELECT DISTINCT V_TOTAL_RCV.ITEM_ID,V_TOTAL_RCV.ITEM_NAME, V_TOTAL_RCV.UM_NAME, V_TOTAL_RCV.STORE_NAME, NVL(SUM(DISTINCT V_TOTAL_RCV.Unit_Value), 0) Unit_Value, (SELECT t74072.T_LANG2_NAME FROM t74073 INNER JOIN t74072 ON t74073.T_COST_TYPE_ID = t74072.T_COST_TYPE_ID WHERE T_ID = V_TOTAL_RCV.ITEM_ID and  t74073.T_COST_TYPE_ID not in(81,104,105)) Item_type, NVL(SUM(DISTINCT RCV_QTY), 0) RCV_QTY, NVL(SUM(ISSUE_QTY), 0) ISSUE_QTY, NVL(fn_Stock_Qty(V_TOTAL_RCV.ITEM_ID, V_TOTAL_RCV.UM_ID, V_TOTAL_RCV.STORE_ID), 0) Stock FROM V_TOTAL_RCV LEFT OUTER JOIN V_TOTAL_ISSUE ON V_TOTAL_RCV.ITEM_ID = V_TOTAL_ISSUE.ITEM_ID AND V_TOTAL_RCV.UM_ID = V_TOTAL_ISSUE.UM_ID AND V_TOTAL_RCV.STORE_ID = V_TOTAL_ISSUE.STORE_ID WHERE V_TOTAL_RCV.STORE_ID = " + storeid+"GROUP BY V_TOTAL_RCV.ITEM_ID, V_TOTAL_RCV.UM_ID, V_TOTAL_RCV.STORE_ID, V_TOTAL_RCV.ITEM_NAME, V_TOTAL_RCV.UM_NAME, V_TOTAL_RCV.STORE_NAME ORDER BY V_TOTAL_RCV.STORE_NAME)t");

        }
    }
}