//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AmbucareContainer : DbContext
    {
        public AmbucareContainer()
            : base("name=AmbucareContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T02003> T02003 { get; set; }
        public virtual DbSet<T02040> T02040 { get; set; }
        public virtual DbSet<T02064> T02064 { get; set; }
        public virtual DbSet<T02065> T02065 { get; set; }
        public virtual DbSet<T06301> T06301 { get; set; }
        public virtual DbSet<T30010> T30010 { get; set; }
        public virtual DbSet<T30209> T30209 { get; set; }
        public virtual DbSet<T74000> T74000 { get; set; }
        public virtual DbSet<T74001> T74001 { get; set; }
        public virtual DbSet<T74002> T74002 { get; set; }
        public virtual DbSet<T74003> T74003 { get; set; }
        public virtual DbSet<T74005> T74005 { get; set; }
        public virtual DbSet<T74006> T74006 { get; set; }
        public virtual DbSet<T74008> T74008 { get; set; }
        public virtual DbSet<T74009> T74009 { get; set; }
        public virtual DbSet<T74010> T74010 { get; set; }
        public virtual DbSet<T74011> T74011 { get; set; }
        public virtual DbSet<T74012> T74012 { get; set; }
        public virtual DbSet<T74013> T74013 { get; set; }
        public virtual DbSet<T74014> T74014 { get; set; }
        public virtual DbSet<T74016> T74016 { get; set; }
        public virtual DbSet<T74017> T74017 { get; set; }
        public virtual DbSet<T74018> T74018 { get; set; }
        public virtual DbSet<T74019> T74019 { get; set; }
        public virtual DbSet<T74020> T74020 { get; set; }
        public virtual DbSet<T74021> T74021 { get; set; }
        public virtual DbSet<T74022> T74022 { get; set; }
        public virtual DbSet<T74023> T74023 { get; set; }
        public virtual DbSet<T74024> T74024 { get; set; }
        public virtual DbSet<T74025> T74025 { get; set; }
        public virtual DbSet<T74026> T74026 { get; set; }
        public virtual DbSet<T74027> T74027 { get; set; }
        public virtual DbSet<T74030> T74030 { get; set; }
        public virtual DbSet<T74031> T74031 { get; set; }
        public virtual DbSet<T74035> T74035 { get; set; }
        public virtual DbSet<T74038> T74038 { get; set; }
        public virtual DbSet<T74039> T74039 { get; set; }
        public virtual DbSet<T74040> T74040 { get; set; }
        public virtual DbSet<T74045> T74045 { get; set; }
        public virtual DbSet<T74046> T74046 { get; set; }
        public virtual DbSet<T74047> T74047 { get; set; }
        public virtual DbSet<T74048> T74048 { get; set; }
        public virtual DbSet<T74049> T74049 { get; set; }
        public virtual DbSet<T74050> T74050 { get; set; }
        public virtual DbSet<T74051> T74051 { get; set; }
        public virtual DbSet<T74052> T74052 { get; set; }
        public virtual DbSet<T74053> T74053 { get; set; }
        public virtual DbSet<T74054> T74054 { get; set; }
        public virtual DbSet<T74055> T74055 { get; set; }
        public virtual DbSet<T74056> T74056 { get; set; }
        public virtual DbSet<T74057> T74057 { get; set; }
        public virtual DbSet<T74058> T74058 { get; set; }
        public virtual DbSet<T74059> T74059 { get; set; }
        public virtual DbSet<T74060> T74060 { get; set; }
        public virtual DbSet<T74061> T74061 { get; set; }
        public virtual DbSet<T74066> T74066 { get; set; }
        public virtual DbSet<T74068> T74068 { get; set; }
        public virtual DbSet<T74069> T74069 { get; set; }
        public virtual DbSet<T74070> T74070 { get; set; }
        public virtual DbSet<T74072> T74072 { get; set; }
        public virtual DbSet<T74073> T74073 { get; set; }
        public virtual DbSet<T74074> T74074 { get; set; }
        public virtual DbSet<T74075> T74075 { get; set; }
        public virtual DbSet<T74077> T74077 { get; set; }
        public virtual DbSet<T74078> T74078 { get; set; }
        public virtual DbSet<T74079> T74079 { get; set; }
        public virtual DbSet<T74080> T74080 { get; set; }
        public virtual DbSet<T74081> T74081 { get; set; }
        public virtual DbSet<T74084> T74084 { get; set; }
        public virtual DbSet<T74085> T74085 { get; set; }
        public virtual DbSet<T74089> T74089 { get; set; }
        public virtual DbSet<T74090> T74090 { get; set; }
        public virtual DbSet<T74093> T74093 { get; set; }
        public virtual DbSet<T74094> T74094 { get; set; }
        public virtual DbSet<T74095> T74095 { get; set; }
        public virtual DbSet<T74096> T74096 { get; set; }
        public virtual DbSet<T74097> T74097 { get; set; }
        public virtual DbSet<T74098> T74098 { get; set; }
        public virtual DbSet<T74101> T74101 { get; set; }
        public virtual DbSet<T74104> T74104 { get; set; }
        public virtual DbSet<T74M01> T74M01 { get; set; }
        public virtual DbSet<T74028> T74028 { get; set; }
        public virtual DbSet<T74102> T74102 { get; set; }
        public virtual DbSet<T74036> T74036 { get; set; }
        public virtual DbSet<T74037> T74037 { get; set; }
        public virtual DbSet<T74004> T74004 { get; set; }
        public virtual DbSet<T74015> T74015 { get; set; }
        public virtual DbSet<T74041> T74041 { get; set; }
        public virtual DbSet<T74120> T74120 { get; set; }
        public virtual DbSet<T74121> T74121 { get; set; }
        public virtual DbSet<T74044> T74044 { get; set; }
        public virtual DbSet<T74043> T74043 { get; set; }
        public virtual DbSet<T74071> T74071 { get; set; }
    }
}
