//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T02065
    {
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public string T_SITE_CODE { get; set; }
        public string T_LANG1_NAME { get; set; }
        public string T_LANG2_NAME { get; set; }
        public string T_ZONE_CODE { get; set; }
        public string T_PERCENT { get; set; }
        public string T_SITE_STATUS { get; set; }
        public string T_RECEIPT_ORDER_NO { get; set; }
        public string T_MUDIRIA { get; set; }
        public string T_BANK_CODE { get; set; }
        public string T_BANK_ACC_NO { get; set; }
        public Nullable<decimal> T_INITIAL_BALANCE { get; set; }
        public Nullable<decimal> T_BALANCE { get; set; }
        public Nullable<decimal> T_LATITUDE { get; set; }
        public Nullable<decimal> T_LONGITUDE { get; set; }
        public string T_EXPENSE_RECEIVE_INTERVAL { get; set; }
        public string T_PREVENTFLAG { get; set; }
        public string T_SPECIAL_FLAG { get; set; }
        public string T_REFERRAL_CODE { get; set; }
    }
}
