//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T02003
    {
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public string T_NTNLTY_CODE { get; set; }
        public string T_LANG1_NAME { get; set; }
        public string T_LANG2_NAME { get; set; }
        public string T_X_LANG1_NAME_SHRT { get; set; }
        public string T_HL7_CODE { get; set; }
        public string T_PRIM_LANG { get; set; }
        public string T_SECOND_LANG { get; set; }
        public string T_LANG_LABEL1 { get; set; }
        public string T_LANG_LABEL2 { get; set; }
        public short T_NTNLTY_ID { get; set; }
        public string T_PHONE_CODE { get; set; }
    }
}
