//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T06301
    {
        public string T_ICD10_MAIN_CODE { get; set; }
        public string T_ICD10_SUB_CODE { get; set; }
        public string T_ICD10_LONG_DESC2 { get; set; }
        public string T_ICD10_LONG_DESC1 { get; set; }
        public string T_ICD10_SHORT_DESC2 { get; set; }
        public string T_ICD10_SHORT_DESC1 { get; set; }
        public string T_ICD10_TYPE { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<int> T_ICD10_LEVEL { get; set; }
        public string T_ICD10_SEX_BOUNDS { get; set; }
        public string T_ICD10_DIAG_BOUNDS { get; set; }
        public string T_ICD10_CODE { get; set; }
    }
}
