//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74014
    {
        public int T_AMBU_REG_ID { get; set; }
        public string T_CHASIS_NO { get; set; }
        public string T_ENGINE_NO { get; set; }
        public string T_WEIGHT { get; set; }
        public string T_REG_IMAGE { get; set; }
        public string T_BARCODE_ID { get; set; }
        public Nullable<short> T_YEAR_MODEL { get; set; }
        public Nullable<short> T_ITEM_COLOR_ID { get; set; }
        public Nullable<short> T_AMB_TYPE_ID { get; set; }
        public Nullable<short> T_BRAND_ID { get; set; }
        public Nullable<System.DateTime> T_REG_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_AMBU_REG_NUM { get; set; }
        public Nullable<int> T_EMP_ID { get; set; }
        public string T_SERIES { get; set; }
    }
}
