//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74043
    {
        public decimal T_PCHECKUP_ID { get; set; }
        public Nullable<int> T_REQUEST_ID { get; set; }
        public string T_DOC_CODE { get; set; }
        public string T_HIGHT { get; set; }
        public string T_WEIGHT { get; set; }
        public string T_BP_SYS { get; set; }
        public string T_BP_DIA { get; set; }
        public string T_TEMP { get; set; }
        public string T_PULS { get; set; }
        public string T_RESP { get; set; }
        public Nullable<System.DateTime> T_TIME { get; set; }
        public string T_OS { get; set; }
        public string T_BSUGAR_F { get; set; }
        public string T_BSUGAR_ABF { get; set; }
        public string T_URINE_TEST { get; set; }
        public string T_ECG_TEST { get; set; }
        public string T_VERIFY_LEVEL { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public string T_CONCIUS_LEVEL { get; set; }
        public string T_TRIAGE_LEVEL { get; set; }
        public string T_BP_MEAN { get; set; }
        public string T_HEART_RATE { get; set; }
        public string T_ECG_TYPE { get; set; }
        public string T_GLUCOSE { get; set; }
        public Nullable<byte> T_SCORE { get; set; }
        public string T_NEXT_REVIEW { get; set; }
    }
}
