//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74057
    {
        public string T_USER_ID { get; set; }
        public string T_PWD { get; set; }
        public Nullable<byte> T_ACTIVE_FLAG { get; set; }
        public Nullable<int> T_EMP_ID { get; set; }
        public Nullable<int> T_COMPANY_ID { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public string T_UPD_DATE { get; set; }
        public string T_SITE_CODE { get; set; }
        public string T_LOGIN_STATUS { get; set; }
        public Nullable<short> T_ROLE_CODE { get; set; }
        public string T_ZONE_CODE { get; set; }
    }
}
