//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74003
    {
        public int T_ITEM_UM_ID { get; set; }
        public string T_LANG2_NAME { get; set; }
        public string T_LANG1_NAME { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public Nullable<int> T_TYPE_ID { get; set; }
        public string T_PCK_FLAG { get; set; }
        public Nullable<short> T_QTY { get; set; }
    }
}
