//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74080
    {
        public int T_TRANSFER_REQ_ID { get; set; }
        public string T_TRANSFER_REQ_NO { get; set; }
        public Nullable<int> T_ISSUE_ID { get; set; }
        public Nullable<System.DateTime> T_REQ_DATE { get; set; }
        public string T_REQ_SET_BY { get; set; }
        public Nullable<int> T_REQ_SET_BY_STORE_ID { get; set; }
        public string T_REQ_SEND_TO { get; set; }
        public Nullable<int> T_SEND_TO_STORE_ID { get; set; }
        public string T_TRANSFER_FOR { get; set; }
        public string T_TRANSFER_DELIVERY_METHOD { get; set; }
        public string T_STATUS { get; set; }
        public string T_IS_ACTIVE { get; set; }
        public string T_IS_APPROVED { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public Nullable<int> T_SUPPLIER_ID { get; set; }
        public Nullable<int> T_CURRENCY_ID { get; set; }
    }
}
