//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74026
    {
        public int ID { get; set; }
        public string T_USER_ID { get; set; }
        public Nullable<System.DateTime> T_ENTRY_TIME { get; set; }
        public Nullable<decimal> T_LATITUDE { get; set; }
        public Nullable<decimal> T_LONGITUDE { get; set; }
        public string T_DEVICES { get; set; }
        public Nullable<int> T_REQUEST_ID { get; set; }
        public Nullable<byte> T_EVENT_ID { get; set; }
    }
}
