//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74066
    {
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_FORM_CODE { get; set; }
        public string T_LANG1_NAME { get; set; }
        public string T_LANG2_NAME { get; set; }
        public string T_VERSION_NO { get; set; }
        public string T_REPORT_FLAG { get; set; }
        public decimal T_FORM_TYPE_ID { get; set; }
        public decimal T_FORM_CODE_ID { get; set; }
        public string T_USER_ID { get; set; }
        public string T_INACTIVE_FLAG { get; set; }
        public Nullable<byte> T_PAGE_TYPE_ID { get; set; }
        public Nullable<byte> T_ORDER { get; set; }
        public string T_TYPE { get; set; }
        public Nullable<short> T_ROLE_CODE { get; set; }
    }
}
