//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74085
    {
        public long T_TRNS_RCV_DTL_ID { get; set; }
        public Nullable<int> T_TRNS_RCV_ID { get; set; }
        public Nullable<int> T_ITEM_ID { get; set; }
        public Nullable<decimal> T_TRNS_QTY { get; set; }
        public Nullable<int> T_UOM_ID { get; set; }
        public Nullable<int> T_CUR_STOCK_ID { get; set; }
        public Nullable<int> T_SUPPLIER_ID { get; set; }
        public string T_RCV_TYPE { get; set; }
        public string T_OTHERS { get; set; }
        public string T_IS_ACTIVE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public Nullable<long> T_TRANSFER_REQ_DTL_ID { get; set; }
    }
}
