//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74049
    {
        public int T_SL_REQ_DTL_ID { get; set; }
        public Nullable<int> T_SL_REQ_ID { get; set; }
        public Nullable<int> T_ITEM_ID { get; set; }
        public Nullable<int> T_ITEM_UM_ID { get; set; }
        public Nullable<decimal> T_SL_QTY { get; set; }
        public Nullable<decimal> T_RCV_QTY { get; set; }
        public string T_PRIORITY { get; set; }
        public string T_SL_STS_DTL { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
    }
}
