//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74004
    {
        public int T_EMP_ID { get; set; }
        public Nullable<int> T_EMP_NO { get; set; }
        public Nullable<System.DateTime> T_BIRTH_DATE { get; set; }
        public Nullable<short> T_MRTL_STATUS_CODE { get; set; }
        public string T_FAMILY_LANG1_NAME { get; set; }
        public string T_FAMILY_LANG2_NAME { get; set; }
        public string T_FATHER_LANG1_NAME { get; set; }
        public string T_FATHER_LANG2_NAME { get; set; }
        public string T_GFATHER_LANG1_NAME { get; set; }
        public string T_GFATHER_LANG2_NAME { get; set; }
        public string T_FIRST_LANG1_NAME { get; set; }
        public string T_FIRST_LANG2_NAME { get; set; }
        public string T_MOTHER_LANG1_NAME { get; set; }
        public string T_MOTHER_LANG2_NAME { get; set; }
        public Nullable<short> T_NTNLTY_ID { get; set; }
        public string T_PASSPORT_NO { get; set; }
        public string T_PHONE_HOME { get; set; }
        public string T_PHONE_WORK { get; set; }
        public string T_MOBILE_NO { get; set; }
        public string T_POSTAL_CODE { get; set; }
        public string T_ADDRESS1 { get; set; }
        public string T_ADDRESS2 { get; set; }
        public Nullable<short> T_RLGN_CODE { get; set; }
        public Nullable<int> T_SEX_CODE { get; set; }
        public string T_COMPANY_CODE { get; set; }
        public Nullable<short> T_BLD_GROUP_ID { get; set; }
        public Nullable<short> T_IP_EPISODES { get; set; }
        public string T_SPONSR_CODE { get; set; }
        public string T_SMOKER_FLAG { get; set; }
        public string T_EMP_LANG { get; set; }
        public string T_INACTIVE_FLAG { get; set; }
        public string T_POLICY_NO { get; set; }
        public string T_ACCEPTED { get; set; }
        public string T_REF_LETTER { get; set; }
        public string T_SKIN_COLOR { get; set; }
        public string T_DISTINCTION { get; set; }
        public string T_FILE_INACTIVE { get; set; }
        public string T_LAST_LANG1_NAME { get; set; }
        public string T_LAST_LANG2_NAME { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_EMAIL_ID { get; set; }
        public Nullable<int> T_BALANCE_AMOUNT { get; set; }
        public string T_EMP_DEATH { get; set; }
        public Nullable<int> T_EMP_TYP_ID { get; set; }
        public Nullable<int> T_DOC_DEPT_ID { get; set; }
        public Nullable<int> T_DOC_DEGREE_ID { get; set; }
        public Nullable<int> T_DOC_SPECI_ID { get; set; }
        public string T_EMP_STATUS { get; set; }
    }
}
