//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74077
    {
        public byte T_PROB_TYPE_ID { get; set; }
        public byte[] T_LOG { get; set; }
        public string T_LANG2_NAME { get; set; }
        public string T_LOG_B64 { get; set; }
    }
}
