//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74054
    {
        public int T_COMPANY_ID { get; set; }
        public string T_LANG1_NAME { get; set; }
        public string T_LANG2_NAME { get; set; }
        public string T_LANG1_ADRS_NAME { get; set; }
        public string T_LANG2_ADRS_NAME { get; set; }
        public string T_EMAIL { get; set; }
        public string T_PHONE { get; set; }
        public string T_WEB_URL { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
    }
}
