//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74036
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T74036()
        {
            this.T74037 = new HashSet<T74037>();
        }
    
        public int T_ISSUE_ID { get; set; }
        public string T_USER_ID { get; set; }
        public Nullable<int> T_COMPANY_ID { get; set; }
        public Nullable<System.DateTime> T_ISSUE_DATE { get; set; }
        public string T_PAT_NO { get; set; }
        public Nullable<int> T_DOC_CODE { get; set; }
        public Nullable<int> T_REQUEST_ID { get; set; }
        public string T_PRSCRPTN_ID { get; set; }
        public string T_ENTRY_USER_ { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE_ { get; set; }
        public string T_UPD_USER_ { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE_ { get; set; }
        public Nullable<int> T_CURRENCY_ID { get; set; }
        public Nullable<int> T_SL_REQ_ID { get; set; }
        public Nullable<int> T_STORE_ID { get; set; }
        public Nullable<decimal> T_DISCOUNT { get; set; }
        public Nullable<decimal> T_TOTAL { get; set; }
        public Nullable<decimal> T_VAT { get; set; }
        public Nullable<decimal> T_GRAND_TOTAL { get; set; }
        public Nullable<int> T_ISSUED_BY { get; set; }
        public Nullable<decimal> T_DIS_AMOUNT { get; set; }
        public string T_ENTRY_TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T74037> T74037 { get; set; }
    }
}
