//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74040
    {
        public int T_PRSCRPTN_DTL_ID { get; set; }
        public Nullable<int> T_PRESCRIPTION_ID { get; set; }
        public string T_ITEM_CODE { get; set; }
        public string T_TRADE_CODE { get; set; }
        public string T_GEN_CODE { get; set; }
        public string T_REQUEST_STRENGTH { get; set; }
        public string T_FORM_ID { get; set; }
        public string T_DRUG_ROUTE_CODE { get; set; }
        public string T_MORNING_DOSE_UNIT { get; set; }
        public string T_NOON_DOSE_UNIT { get; set; }
        public string T_NIGHT_DOSE_UNIT { get; set; }
        public string T_MEAL_INSTRUCTION { get; set; }
        public string T_INS_TIME { get; set; }
        public string T_SATURDAY { get; set; }
        public string T_SUNDAY { get; set; }
        public string T_MONDAY { get; set; }
        public string T_TUESDAY { get; set; }
        public string T_WEDNESDAY { get; set; }
        public string T_THURSDAY { get; set; }
        public string T_FRIDAY { get; set; }
        public string T_REMARKS_DTL { get; set; }
        public string T_FREQUENCY_CODE { get; set; }
        public string T_FREQUENCY_INS_ID { get; set; }
        public string T_DOSE_DURATION_CODE { get; set; }
        public string T_DOSE_DURATION_INS_ID { get; set; }
        public string T_DRUG_INACTIVE_FLAG { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
    }
}
