//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74046
    {
        public int T_PAT_ID { get; set; }
        public string T_PAT_NO { get; set; }
        public Nullable<System.DateTime> T_BIRTH_DATE { get; set; }
        public Nullable<short> T_MRTL_STATUS { get; set; }
        public string T_FATHER_LANG1_NAME { get; set; }
        public string T_FATHER_LANG2_NAME { get; set; }
        public string T_GFATHER_LANG1_NAME { get; set; }
        public string T_GFATHER_LANG2_NAME { get; set; }
        public string T_FIRST_LANG1_NAME { get; set; }
        public string T_FIRST_LANG2_NAME { get; set; }
        public string T_MOTHER_LANG1_NAME { get; set; }
        public string T_MOTHER_LANG2_NAME { get; set; }
        public Nullable<short> T_NTNLTY_ID { get; set; }
        public string T_PASSPORT_NO { get; set; }
        public string T_PHONE_HOME { get; set; }
        public string T_PHONE_WORK { get; set; }
        public string T_MOBILE_NO { get; set; }
        public string T_POSTAL_CODE { get; set; }
        public string T_ADDRESS1 { get; set; }
        public string T_ADDRESS2 { get; set; }
        public Nullable<short> T_RLGN_CODE { get; set; }
        public Nullable<int> T_SEX_CODE { get; set; }
        public string T_BLD_GRP { get; set; }
        public string T_JOB_CODE { get; set; }
        public string T_SPONSR_CODE { get; set; }
        public Nullable<decimal> T_BALANCE_AMOUNT { get; set; }
        public string T_NEW_PATNO { get; set; }
        public string T_PAT_TYPE { get; set; }
        public string T_FORM_NAME { get; set; }
        public string T_SMOKER_FLAG { get; set; }
        public string T_CNCL_NTNLTY_ID { get; set; }
        public string T_EMAIL_ID { get; set; }
        public string T_INACTIVE_FLAG { get; set; }
        public string T_SKIN_COLOR { get; set; }
        public string T_NAME1 { get; set; }
        public string T_NAME2 { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public Nullable<int> T_EMP_DESI_ID { get; set; }
        public string T_OFFICE_NAME { get; set; }
        public Nullable<decimal> T_NATIONAL_ID { get; set; }
        public string T_FAMILY_LANG1_NAME { get; set; }
        public string T_FAMILY_LANG2_NAME { get; set; }
        public string T_ALT_MOBILE_NO { get; set; }
        public string T_IDENTITY_ID { get; set; }
        public string T_SOCIAL_NO { get; set; }
    }
}
