//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74095
    {
        public int T_PROB_DET_ID { get; set; }
        public Nullable<int> T_ORDER_ID { get; set; }
        public string T_PROB_DELT_LANG1 { get; set; }
        public string T_PROB_DELT_LANG2 { get; set; }
        public Nullable<System.DateTime> T_APR_DELV_DATE { get; set; }
        public string T_REPAIR_STATUS { get; set; }
        public string T_REPAIR_INST_DELT { get; set; }
        public Nullable<System.DateTime> T_REPAIR_DATE { get; set; }
        public Nullable<int> T_REPAIRER_ID { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
    }
}
