//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74041
    {
        public int T_REQUEST_ID { get; set; }
        public Nullable<int> T_COMPANY_ID { get; set; }
        public Nullable<int> T_PAT_ID { get; set; }
        public string T_USER_ID { get; set; }
        public Nullable<decimal> T_ALLERGY_CODE { get; set; }
        public string T_ARRIVAL_STATUS { get; set; }
        public Nullable<int> T_CH_COMP { get; set; }
        public string T_DISCH_RSN_CODE { get; set; }
        public string T_DISCHARGE_DOC_CODE { get; set; }
        public string T_DISCH_DEST { get; set; }
        public string T_ADMIT_DOC_CODE { get; set; }
        public string T_TRIAGE_CONDITION { get; set; }
        public Nullable<System.DateTime> T_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> T_REQUEST_TIME { get; set; }
        public string T_EPISODE_NO { get; set; }
        public string T_PROBLEM { get; set; }
        public string T_PROBLEM_DURATION { get; set; }
        public string T_SMOKING { get; set; }
        public string T_PREGNANCY { get; set; }
        public string T_TRAUMA { get; set; }
        public string T_DISCH_RSN_REMARKS { get; set; }
        public string T_EPISODE_END_TIME { get; set; }
        public string T_DISCH_STATUS { get; set; }
        public Nullable<System.DateTime> T_DISCHARGE_TIME { get; set; }
        public Nullable<System.DateTime> T_DISCHARGE_DATE { get; set; }
        public string T_COMMENTS { get; set; }
        public string T_RED_CRESCENT { get; set; }
        public string T_ELIGIBLE { get; set; }
        public string T_PHYSICAL_EXAM { get; set; }
        public string T_PROVISIONAL_DIAG { get; set; }
        public string T_INVESTIGATIONS { get; set; }
        public Nullable<System.DateTime> T_SEEN_DATE { get; set; }
        public Nullable<System.DateTime> T_SEEN_TIME { get; set; }
        public Nullable<System.DateTime> T_TRIAGE_OUT_DATE { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public Nullable<decimal> T_LATITUDE { get; set; }
        public string T_LONGITUDE { get; set; }
        public string T_APPRX_TIME { get; set; }
        public string T_APPRX_DIST { get; set; }
        public Nullable<short> T_PROB_TYPE_ID { get; set; }
        public string T_PROB_DETAILS { get; set; }
        public Nullable<int> T_AMBU_REG_ID { get; set; }
        public string T_AGE { get; set; }
        public string T_CANCEL_STATUS { get; set; }
        public string T_CANCEL_REASON { get; set; }
        public string T_ICD10_CODE { get; set; }
        public Nullable<System.DateTime> T_ASSIGN_TIME { get; set; }
        public Nullable<System.DateTime> T_ACCEPT_TIME { get; set; }
        public string T_REFER_SITE_DOC { get; set; }
        public Nullable<System.DateTime> T_REFER_TIME { get; set; }
        public string T_ACCEPT_STATUS { get; set; }
        public string T_REF_DOC_CODE { get; set; }
        public Nullable<System.DateTime> T_REF_DOC_TIME { get; set; }
        public string T_SITE_DIS_CODE { get; set; }
        public Nullable<System.DateTime> T_START_TIME { get; set; }
        public string T_CHAT_DOC_ID { get; set; }
        public string T_CHAT_FLAG { get; set; }
        public Nullable<int> T_REF_ID { get; set; }
        public string T_TEAM_SITE_CODE { get; set; }
        public Nullable<System.DateTime> T_DOC_REQ_ACPT_DATE { get; set; }
        public string T_MAP_LOC { get; set; }
        public Nullable<System.DateTime> T_CAN_DATE { get; set; }
        public Nullable<byte> T_TRIAGE_LEVEL { get; set; }
        public Nullable<byte> T_EYE_OPEN { get; set; }
        public Nullable<byte> T_BEST_MOTOR { get; set; }
        public Nullable<byte> T_VERBAL_RESPONSE { get; set; }
        public string T_OPER_CNCL_FLAG { get; set; }
        public Nullable<System.DateTime> T_OPER_CNCL_DATE { get; set; }
        public string T_OPER_DES_CODE { get; set; }
        public Nullable<System.DateTime> T_OPER_DES_TIME { get; set; }
        public Nullable<System.DateTime> T_OPER_ACPT_DATE { get; set; }
        public Nullable<System.DateTime> T_TEAM_ARVL_HOS { get; set; }
        public Nullable<System.DateTime> T_TEAM_DEPT_HOS { get; set; }
        public Nullable<System.DateTime> T_TEAM_ARVL_STN { get; set; }
        public Nullable<System.DateTime> T_PANIC_TIME { get; set; }
        public Nullable<System.DateTime> T_CASE_ARRIVAL { get; set; }
        public Nullable<byte> T_EVENT_FLAG { get; set; }
        public Nullable<System.DateTime> T_RDY_FOR_NXT_PAT { get; set; }
        public Nullable<System.DateTime> T_PAT_REQ_CNCL { get; set; }
        public string T_VERIFY_DISCHARGE { get; set; }
        public string T_REMARKS { get; set; }
        public Nullable<long> T_PROTOCAL_NO { get; set; }
        public string T_CLIT_ID { get; set; }
        public string T_PUPILLER_ID { get; set; }
        public string T_ACTV_OPER { get; set; }
        public Nullable<long> T_CALLER_ID { get; set; }
        public Nullable<short> T_CALL_REASON_ID { get; set; }
    }
}
