//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74084
    {
        public int T_TRNS_RCV_ID { get; set; }
        public string T_TRNS_RCV_NO { get; set; }
        public Nullable<System.DateTime> T_RCV_DATE { get; set; }
        public string T_RCV_FRM { get; set; }
        public Nullable<int> T_RCV_FRM_STR_ID { get; set; }
        public string T_RCV_TO { get; set; }
        public Nullable<int> T_RCV_TO_STR_ID { get; set; }
        public string T_RCV_STATUS { get; set; }
        public string T_IS_APPROVED { get; set; }
        public Nullable<int> T_CURRENCY_ID { get; set; }
        public Nullable<decimal> T_UNIT_VALUE { get; set; }
        public Nullable<decimal> T_TOTAL_VALUE { get; set; }
        public Nullable<decimal> T_CONVERTION_VALUE_TK { get; set; }
        public string T_LOT_NO { get; set; }
        public string T_BATCH { get; set; }
        public Nullable<int> T_COUNTRY_ID { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public Nullable<int> T_TRANSFER_REQ_ID { get; set; }
    }
}
