//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74098
    {
        public decimal T_AUTO_ID { get; set; }
        public string T_SENDER_ID { get; set; }
        public string T_RECIEVER_ID { get; set; }
        public string T_SENDER_TYPE { get; set; }
        public string T_TEXT { get; set; }
        public Nullable<System.DateTime> T_TIME { get; set; }
        public Nullable<decimal> T_REF_ID { get; set; }
        public string T_FILE_LOC { get; set; }
        public Nullable<int> T_REQUEST_ID { get; set; }
        public string T_RECEIVED_FLAG { get; set; }
    }
}
