//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74037
    {
        public long T_ISSUE_DTL_ID { get; set; }
        public Nullable<int> T_ISSUE_ID { get; set; }
        public Nullable<int> T_CUR_STOCK_ID { get; set; }
        public Nullable<int> T_ITEM_ID { get; set; }
        public Nullable<decimal> T_QUANTITY { get; set; }
        public Nullable<System.DateTime> T_EXPIRE_DATE { get; set; }
        public Nullable<int> T_UOM_ID { get; set; }
        public Nullable<decimal> T_SALE_PRICE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE_ { get; set; }
        public string T_UPD_USER_ { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE_ { get; set; }
        public Nullable<decimal> T_TOTAL_AMOUNT { get; set; }
        public Nullable<int> T_SL_REQ_DTL_ID { get; set; }
        public string T_PCS_BOX { get; set; }
        public Nullable<decimal> T_DISCOUNT { get; set; }
    
        public virtual T74027 T74027 { get; set; }
        public virtual T74036 T74036 { get; set; }
    }
}
