//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74027
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T74027()
        {
            this.T74037 = new HashSet<T74037>();
        }
    
        public int T_CUR_STOCK_ID { get; set; }
        public Nullable<int> T_COMPANY_ID { get; set; }
        public Nullable<int> T_ITEM_ID { get; set; }
        public Nullable<decimal> T_UNIT_VALUE { get; set; }
        public Nullable<decimal> T_TOTAL_VALUE { get; set; }
        public Nullable<decimal> T_PURCHASE_QTY { get; set; }
        public Nullable<decimal> T_TRNSACTION_QTY { get; set; }
        public Nullable<int> T_STORE_ID { get; set; }
        public Nullable<System.DateTime> T_STOCK_DATE { get; set; }
        public string T_ENTRY_USER_ { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE_ { get; set; }
        public string T_UPD_USER_ { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE_ { get; set; }
        public Nullable<System.DateTime> T_EXPIRE_DATE { get; set; }
        public Nullable<System.DateTime> T_MF_DATE { get; set; }
        public Nullable<long> T_PR_RCV_DTL_ID { get; set; }
        public Nullable<int> T_STOCK_TYPE_ID { get; set; }
        public string T_LOT_NO { get; set; }
        public string T_BATCH { get; set; }
        public Nullable<int> T_SUPPLIER_ID { get; set; }
        public Nullable<int> T_ITEM_UM_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T74037> T74037 { get; set; }
    }
}
