//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74025
    {
        public int T_USER_TYPE_ID { get; set; }
        public string T_TYPE_NAME1 { get; set; }
        public string T_TYPE_NAME2 { get; set; }
        public string T_ENTRY_USER { get; set; }
        public string T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public string T_UPD_DATE { get; set; }
    }
}
