//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74053
    {
        public string T_SITE_NO { get; set; }
        public string T_ZONE_CODE { get; set; }
        public string T_SITE_CODE { get; set; }
        public string T_LANG1_NAME { get; set; }
        public string T_LANG2_NAME { get; set; }
        public string T_CONTACT_NAME { get; set; }
        public string T_CONTACT_MOBILE { get; set; }
        public string T_SITE_URL { get; set; }
        public Nullable<decimal> T_LATITUDE { get; set; }
        public Nullable<decimal> T_LONGITUDE { get; set; }
        public string T_MUDIRIA { get; set; }
        public string T_SITE_STATUS { get; set; }
        public string T_IMPLEMENTATION_YEAR { get; set; }
        public string T_PRIVATE_FLAG { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
    }
}
