//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74028
    {
        public decimal T_PUR_REQ_ID { get; set; }
        public Nullable<int> T_COMPANY_ID { get; set; }
        public string T_USER_ID { get; set; }
        public Nullable<System.DateTime> T_PURCHASE_DATE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_PURCHASE_NO { get; set; }
    }
}
