//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74089
    {
        public int T_PRICE_ID { get; set; }
        public Nullable<int> T_COST_TYPE_DTL_ID { get; set; }
        public Nullable<decimal> T_PUR_PRICE { get; set; }
        public Nullable<decimal> T_SALE_PRICE { get; set; }
        public Nullable<int> T_ITEM_UM_ID { get; set; }
        public Nullable<decimal> T_RET_PRCNTG { get; set; }
        public Nullable<decimal> T_INCRS_DCRS_PRCNTG { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_ACTIVE { get; set; }
    }
}
