//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74081
    {
        public long T_TRANSFER_REQ_DTL_ID { get; set; }
        public Nullable<int> T_TRANSFER_REQ_ID { get; set; }
        public Nullable<int> T_ITEM_ID { get; set; }
        public Nullable<decimal> T_TRANSFER_QTY { get; set; }
        public Nullable<int> T_UOM_ID { get; set; }
        public Nullable<int> T_CUR_STOCK_ID { get; set; }
        public string T_RECEIVE_TYPE { get; set; }
        public Nullable<decimal> T_UNIT_VALUE { get; set; }
        public Nullable<decimal> T_TOTAL_VALUE { get; set; }
        public Nullable<decimal> T_CONVERTION_VALUE_TK { get; set; }
        public string T_OTHERS { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public string T_TRANSFER_PRORITY { get; set; }
        public string T_LOT_NO { get; set; }
        public string T_BATCH { get; set; }
    }
}
