//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74048
    {
        public int T_SL_REQ_ID { get; set; }
        public Nullable<int> T_COMPANY_ID { get; set; }
        public Nullable<int> T_SUPPLIER_ID { get; set; }
        public Nullable<int> T_STR_FR_ID { get; set; }
        public Nullable<int> T_STR_TO_ID { get; set; }
        public string T_SL_REQ_NO { get; set; }
        public Nullable<System.DateTime> T_SL_REQ_DATE { get; set; }
        public string T_SL_REQ_STATUS { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
        public Nullable<System.DateTime> T_EXP_DLVRY_DATE { get; set; }
        public Nullable<int> T_CURRENCY_ID { get; set; }
        public Nullable<int> T_REQ_PERSON_ID { get; set; }
    }
}
