//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74044
    {
        public int T_STORE_ID { get; set; }
        public Nullable<int> T_AMBU_REG_ID { get; set; }
        public string T_LANG1_NAME { get; set; }
        public string T_LANG2_NAME { get; set; }
        public Nullable<int> T_AREA { get; set; }
        public Nullable<decimal> T_PRICE { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
    }
}
