//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmbucareDAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class T74120
    {
        public long T_CALLER_ID { get; set; }
        public string T_FIRST_LANG1_NAME { get; set; }
        public string T_FIRST_LANG2_NAME { get; set; }
        public string T_LAST_LANG1_NAME { get; set; }
        public string T_LAST_LANG2_NAME { get; set; }
        public Nullable<short> T_NTNLTY_ID { get; set; }
        public string T_PASSPORT_NO { get; set; }
        public string T_MOBILE_NO { get; set; }
        public string T_ADDRESS { get; set; }
        public string T_ENTRY_USER { get; set; }
        public Nullable<System.DateTime> T_ENTRY_DATE { get; set; }
        public string T_UPD_USER { get; set; }
        public Nullable<System.DateTime> T_UPD_DATE { get; set; }
    }
}
