using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;

namespace AmbucareDAL.Repository.DAL.Setup
{
    public class T74143DAL:CommonDAL
    {
        public DataTable getAllGridData(string lang, string zoneCode)
        {
            //DataTable query = Query($"SELECT K.*, DECODE(K.T_LOGIN_STATUS, NULL, 'Logged Out', 'Logged In') T_LOGIN_STATUS_DESC, (CASE WHEN (K.T_DISCH_STATUS IS NULL AND K.T_REQUEST_ID IS NULL) THEN 'Request Not Created' WHEN (K.T_DISCH_STATUS IS NULL AND K.T_REQUEST_ID IS NOT NULL) THEN 'In Ambulance' WHEN (K.T_DISCH_STATUS IS NOT NULL AND K.T_REQUEST_ID IS NOT NULL) THEN 'Discharged' END) T_DISCH_STATUS_DESC, T41.T_CHAT_DOC_ID, T04.T_FIRST_LANG{lang}_NAME || ' ' || T04.T_FATHER_LANG{lang}_NAME || ' ' || T04.T_GFATHER_LANG{lang}_NAME T_DOCTOR_NAME, T04.T_MOBILE_NO FROM (SELECT DISTINCT T57.T_USER_ID, T_LOGIN_STATUS, (SELECT T_DISCH_STATUS FROM T74041 WHERE T74041.T_REQUEST_ID = (SELECT MAX(T_REQUEST_ID) FROM T74041 T WHERE T.T_USER_ID = T57.T_USER_ID)) T_DISCH_STATUS, (SELECT T_REQUEST_ID FROM T74041 WHERE T74041.T_REQUEST_ID = (SELECT MAX(T_REQUEST_ID) FROM T74041 T WHERE T.T_USER_ID = T57.T_USER_ID)) T_REQUEST_ID, T04.T_FIRST_LANG{lang}_NAME || ' ' || T04.T_FATHER_LANG{lang}_NAME || ' ' || T04.T_GFATHER_LANG{lang}_NAME T_OPERATOR_NAME FROM T74057 T57 INNER JOIN T74004 T04 ON T04.T_EMP_ID = T57.T_EMP_ID WHERE T57.T_ROLE_CODE = 24 AND T04.T_EMP_TYP_ID = 21) K LEFT JOIN t74041 t41 ON T41.T_REQUEST_ID = K.T_REQUEST_ID LEFT JOIN t74057 t57 ON T41.T_CHAT_DOC_ID = T57.T_USER_ID AND T57.T_ROLE_CODE = 81 LEFT JOIN t74004 t04 ON T04.T_EMP_ID = T57.T_EMP_ID WHERE T57.T_ZONE_CODE='{zoneCode}' ORDER BY T_LOGIN_STATUS_DESC");
            

            DataTable query = Query($"select l.* from(SELECT K.*, DECODE(K.T_LOGIN_STATUS, NULL, 'Logged Out', 'Logged In') T_LOGIN_STATUS_DESC, ( CASE WHEN (K.T_DISCH_STATUS IS NULL AND K.T_REQUEST_ID IS NULL) THEN 'Request Not Created' WHEN (K.T_DISCH_STATUS IS NULL AND K.T_REQUEST_ID IS NOT NULL) THEN 'In Ambulance' WHEN (K.T_DISCH_STATUS IS NOT NULL AND K.T_REQUEST_ID IS NOT NULL) THEN 'Discharged' END) T_DISCH_STATUS_DESC, T41.T_CHAT_DOC_ID, T04.T_FIRST_LANG{lang}_NAME || ' ' || T04.T_FATHER_LANG{lang}_NAME || ' ' || T04.T_GFATHER_LANG{lang}_NAME T_DOCTOR_NAME, T04.T_MOBILE_NO,( CASE WHEN K.T_LOGIN_STATUS IS NULL THEN 'loginIcon.png' else 'LogOut-192.png' end) IMAGE_SHOW FROM (SELECT DISTINCT T57.T_USER_ID,t57.T_ZONE_CODE, T_LOGIN_STATUS, (SELECT T_DISCH_STATUS FROM T74041 WHERE T74041.T_REQUEST_ID = (SELECT MAX(T_REQUEST_ID) FROM T74041 T WHERE T.T_USER_ID = T57.T_USER_ID ) ) T_DISCH_STATUS, (SELECT T_REQUEST_ID FROM T74041 WHERE T74041.T_REQUEST_ID = (SELECT MAX(T_REQUEST_ID) FROM T74041 T WHERE T.T_USER_ID = T57.T_USER_ID ) ) T_REQUEST_ID, T04.T_FIRST_LANG{lang}_NAME || ' ' || T04.T_FATHER_LANG{lang}_NAME || ' ' || T04.T_GFATHER_LANG{lang}_NAME T_OPERATOR_NAME FROM T74057 T57 INNER JOIN T74004 T04 ON T04.T_EMP_ID = T57.T_EMP_ID WHERE T57.T_ROLE_CODE = 24 AND T04.T_EMP_TYP_ID = 21 ) K LEFT JOIN t74041 t41 ON T41.T_REQUEST_ID = K.T_REQUEST_ID LEFT JOIN t74057 t57 ON T41.T_CHAT_DOC_ID = T57.T_USER_ID AND T57.T_ROLE_CODE = 81 LEFT JOIN t74004 t04 ON T04.T_EMP_ID = T57.T_EMP_ID ORDER BY T_LOGIN_STATUS_DESC) l WHERE l.T_ZONE_CODE='{zoneCode}'");
            return query;
        }



        
    }
}